### ISSUE TITLE
TypeScript Language Server Hangs on Completion Resolution On Enter Key Pressed

### ISSUE THREAD

**Issue by babucarr32** [typescript-language-server/typescript-language-server#1014]
## Environment
- Editor: Helix (version 25.07.1 (a05c151b))
- TypeScript version: 5.0.0
- Language Server: TypeScript LSP

## Issue Description
The TypeScript language server frequently hangs when resolving completion details, specifically during `foo.bar` style autocompletion. The hang occurs in the `interruptGetErr` call and can last 15-32 seconds before timing out.

## Reproduction Steps
1. Open a TypeScript file in Helix
2. Type `foo.` to trigger completion
3. Select a completion item that requires detail resolution
4. Hit enter
5. Language server hangs for ~18 seconds

The issue appears to be in the completion resolution pipeline:

```typescript
// src/lsp-server.ts
async completionResolve(item: lsp.CompletionItem, token?: lsp.CancellationToken): Promise<lsp.CompletionItem> {
    // ...
    const response = await this.tsClient.interruptGetErr(() => 
        this.tsClient.execute(CommandTypes.CompletionDetails, cachedData, token)
    );
    // ...
}
```

## Personal debugging log . See time difference between `startTime` and `endTime`
```
{"serverState":1,"running":true,"errored":false,"none":false}
{"serverState":1,"running":true,"errored":false,"none":false}
{"command":"completionEntryDetails","cachedData":{"file":"/path/to/project/users-table/columns.tsx","line":14,"offset":26,"entryNames":["staticStatusText"]},"token":{"_isCancelled":false}}
{"startTime":"Wed Sep 24 2025 20:32:37 GMT+0000 (Greenwich Mean Time)"}
{"serverState":1,"running":true,"errored":false,"none":false}
{"serverState":1,"running":true,"errored":false,"none":false}
{"command":"completionEntryDetails","cachedData":{"file":"/path/to/project/users-table/columns.tsx","line":14,"offset":26,"entryNames":["staticStatusText"]},"token":{"_isCancelled":false}}
{"startTime":"Wed Sep 24 2025 20:32:37 GMT+0000 (Greenwich Mean Time)"}
{"serverState":1,"running":true,"errored":false,"none":false}
{"serverState":1,"running":true,"errored":false,"none":false}
{"endTime":"Wed Sep 24 2025 20:32:55 GMT+0000 (Greenwich Mean Time)"}
Returned item
{"data":{"file":"/path/to/project/users-table/columns.tsx","line":14,"offset":26,"entryNames":["staticStatusText"]},"kind":5,"label":"staticStatusText","sortText":"11","textEdit":{"insert":{"end":{"character":25,"line":13},"start":{"character":16,"line":13}},"newText":"staticStatusText","replace":{"end":{"character":25,"line":13},"start":{"character":16,"line":13}}},"detail":"(property) staticStatusText: (accessor: AccessorEntity<Transaction>, config: StatusColumnConfig) => ColumnDef<Transaction, unknown>","documentation":{"kind":"markdown","value":"Status column using Status component"}}
{"endTime":"Wed Sep 24 2025 20:32:55 GMT+0000 (Greenwich Mean Time)"}
Returned item
{"data":{"file":"/path/to/project/users-table/columns.tsx","line":14,"offset":26,"entryNames":["staticStatusText"]},"kind":5,"label":"staticStatusText","sortText":"11","textEdit":{"insert":{"end":{"character":25,"line":13},"start":{"character":16,"line":13}},"newText":"staticStatusText","replace":{"end":{"character":25,"line":13},"start":{"character":16,"line":13}}},"detail":"(property) staticStatusText: (accessor: AccessorEntity<Transaction>, config: StatusColumnConfig) => ColumnDef<Transaction, unknown>","documentation":{"kind":"markdown","value":"Status column using Status component"}}
{"serverState":1,"running":true,"errored":false,"none":false}
```

## Logs from helix (~/.cache/helix/helix.log)
```
 2025-09-24T21:46:40.643 helix_lsp::transport [INFO] typescript-language-server -> {"jsonrpc":"2.0","method":"completionItem/resolve","params":{"data":{"cacheId":31},"filterText":".staticStatusText","kind":5,"label":"staticStatusText","sortText":"11","textEdit":{"newText":".staticStatusText","range":{"end":{"character":16,"line":12},"start":{"character":15,"line":12}}}},"id":6}
2025-09-24T21:46:40.754 helix_lsp::transport [INFO] typescript-language-server -> {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":{"end":{"character":22,"line":12},"start":{"character":15,"line":12}},"text":"."}],"textDocument":{"uri":"file:///file/path/users-table/columns.tsx","version":11}}}
2025-09-24T21:46:40.754 helix_lsp::transport [INFO] vscode-eslint-language-server -> {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":{"end":{"character":22,"line":12},"start":{"character":15,"line":12}},"text":"."}],"textDocument":{"uri":"file:///file/path/users-table/columns.tsx","version":11}}}
2025-09-24T21:46:40.754 helix_lsp::transport [INFO] typescript-language-server -> {"jsonrpc":"2.0","method":"completionItem/resolve","params":{"data":{"cacheId":31},"filterText":".staticStatusText","kind":5,"label":"staticStatusText","sortText":"11","textEdit":{"newText":".staticStatusText","range":{"end":{"character":16,"line":12},"start":{"character":15,"line":12}}}},"id":7}
2025-09-24T21:46:40.754 helix_lsp::transport [INFO] tailwindcss-ls -> {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"text":"import { Transaction } from '@shared/types/__generated_types__';\n\nimport { createColumnFactory } from '../../../shared-ui/table-columns';\n\nconst columnFactory = createColumnFactory<Transaction>();\n\nconst columns = [\n  columnFactory.customer('customer', { header: 'Customer' }),\n  columnFactory.amount('amount', { header: 'Amount' }),\n  columnFactory.text('transactionType.name', {\n    header: 'Transaction Type',\n  }),\n  columnFactory.('paymentMethodService'),\n  columnFactory.statusByValue('transactionStatus.slug', {\n    header: 'Status',\n  }),\n  columnFactory.date('createdAt', { header: 'Date' }),\n];\n\nexport default columns;\n"}],"textDocument":{"uri":"file:///file/path/users-table/columns.tsx","version":11}}}
2025-09-24T21:46:40.754 helix_lsp::transport [INFO] emmet-ls -> {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":{"end":{"character":22,"line":12},"start":{"character":15,"line":12}},"text":"."}],"textDocument":{"uri":"file:///file/path/users-table/columns.tsx","version":11}}}
2025-09-24T21:46:41.260 helix_lsp::transport [INFO] tailwindcss-ls <- {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///file/path/users-table/columns.tsx","diagnostics":[]}}
2025-09-24T21:46:53.631 helix_lsp::transport [INFO] vscode-eslint-language-server <- {"jsonrpc":"2.0","method":"eslint/status","params":{"uri":"file:///file/path/users-table/columns.tsx","state":1}}
2025-09-24T21:46:57.917 helix_lsp::transport [INFO] typescript-language-server <- {"jsonrpc":"2.0","id":6,"result":{"data":{"file":"/file/path/users-table/columns.tsx","line":13,"offset":17,"entryNames":["staticStatusText"]},"filterText":".staticStatusText","kind":5,"label":"staticStatusText","sortText":"11","textEdit":{"newText":".staticStatusText","range":{"end":{"character":16,"line":12},"start":{"character":15,"line":12}}},"detail":"(property) staticStatusText: (accessor: AccessorEntity<Transaction>, config: StatusColumnConfig) => ColumnDef<Transaction, unknown>","documentation":{"kind":"markdown","value":"Status column using Status component"}}}
2025-09-24T21:47:00.757 helix_term::ui::completion [ERROR] Failed to resolve completion item: request 7 timed out
2025-09-24T21:47:00.757 helix_lsp::transport [INFO] typescript-language-server -> {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":{"end":{"character":16,"line":12},"start":{"character":15,"line":12}},"text":".staticStatusText"}],"textDocument":{"uri":"file:///file/path/users-table/columns.tsx","version":12}}}
```
From the logs above, when the LSP hangs, it resorts to the following error from helix, based on my analysis (id 7)
```
2025-09-24T21:47:00.757 helix_term::ui::completion [ERROR] Failed to resolve completion item: request 7 timed out
```

Autocomplete example 
1. type `staticSta` 
2. select`staticStatusText`
3. hit the `enter key`.

```tsx 
// file/path/users-table/columns.tsx
...
import { createColumnFactory } from '../../../shared-ui/table-columns';

const columnFactory = createColumnFactory<Transaction>();

const columns = [~
...
  columnFactory.statusByValue('transactionStatus.slug', {
    header: 'Status',
  }),
  columnFactory.date('createdAt', { header: 'Date' }),
...
];

export default columns;
```
This problem is slowing me down so much. Any solution this will be highly appreciated.
Thanks.

**Comment by babucarr32** [comment]
Please find some of the tsserver logs here
Both `logVerbosity` and `trace` is set to `verbose`
```
Info 1503 [09:57:35.682] -----------------------------------------------
Info 1503 [09:57:35.682] Project '/path/to/my/project/tsconfig.app.json' (Configured)
Info 1503 [09:57:35.682] 	Files (4473)

Info 1503 [09:57:35.682] -----------------------------------------------
Info 1503 [09:57:35.682] Open files: 
Info 1503 [09:57:35.682] 	FileName: /path/to/my/project/users-table/columns.tsx ProjectRootPath: /path/to/my/preoject
Info 1503 [09:57:35.682] 		Projects: /path/to/my/project/tsconfig.app.json
Perf 1503 [09:57:35.682] 3::open: async elapsed time (in milliseconds) 4766.2830
Info 1504 [09:57:35.683] event:
    {"seq":0,"type":"event","event":"typingsInstallerPid","body":{"pid":24376}}
Info 1505 [09:57:35.686] request:
    {
      "seq": 4,
      "type": "request",
      "command": "geterr",
      "arguments": {
        "delay": 0,
        "files": [
          "/path/to/my/project/users-table/columns.tsx"
        ]
      }
    }
Perf 1506 [09:57:35.686] 4::geterr: async elapsed time (in milliseconds) 0.5571
Info 1507 [09:57:35.688] event:
    {"seq":0,"type":"event","event":"syntaxDiag","body":{"file":"/path/to/my/project/users-table/columns.tsx","diagnostics":[]}}
Info 1508 [09:57:45.341] event:
    {"seq":0,"type":"event","event":"semanticDiag","body":{"file":"/path/to/my/project/users-table/columns.tsx","diagnostics":[]}}
Info 1509 [09:57:45.342] event:
    {"seq":0,"type":"event","event":"suggestionDiag","body":{"file":"/path/to/my/project/users-table/columns.tsx","diagnostics":[]}}
Info 1510 [09:57:45.343] event:
    {"seq":0,"type":"event","event":"requestCompleted","body":{"request_seq":4}}
Info 1511 [09:57:58.424] request:
    {
      "seq": 5,
      "type": "request",
      "command": "configure",
      "arguments": {
        "file": "/path/to/my/project/users-table/columns.tsx",
        "formatOptions": {
          "newLineCharacter": "\n"
        },
        "preferences": {
          "allowIncompleteCompletions": true,
          "allowRenameOfImportPath": true,
          "allowTextChangesInNewFiles": true,
          "autoImportFileExcludePatterns": [],
          "autoImportSpecifierExcludeRegexes": [],
          "disableLineTextInReferences": true,
          "disableSuggestions": false,
          "displayPartsForJSDoc": true,
          "excludeLibrarySymbolsInNavTo": true,
          "generateReturnInDocTemplate": true,
          "importModuleSpecifierEnding": "auto",
          "importModuleSpecifierPreference": "shortest",
          "includeAutomaticOptionalChainCompletions": true,
          "includeCompletionsForImportStatements": true,
          "includeCompletionsForModuleExports": true,
          "includeCompletionsWithClassMemberSnippets": true,
          "includeCompletionsWithInsertText": true,
          "includeCompletionsWithObjectLiteralMethodSnippets": true,
          "includeCompletionsWithSnippetText": true,
          "includeInlayEnumMemberValueHints": true,
          "includeInlayFunctionLikeReturnTypeHints": true,
          "includeInlayFunctionParameterTypeHints": true,
          "includeInlayParameterNameHints": "all",
          "includeInlayParameterNameHintsWhenArgumentMatchesName": true,
          "includeInlayPropertyDeclarationTypeHints": true,
          "includeInlayVariableTypeHints": true,
          "includeInlayVariableTypeHintsWhenTypeMatchesName": false,
          "includePackageJsonAutoImports": "auto",
          "interactiveInlayHints": true,
          "jsxAttributeCompletionStyle": "auto",
          "lazyConfiguredProjectsFromExternalProject": false,
          "maximumHoverLength": 500,
          "organizeImportsAccentCollation": true,
          "organizeImportsCaseFirst": false,
          "organizeImportsCollation": "ordinal",
          "organizeImportsLocale": "en",
          "organizeImportsIgnoreCase": "auto",
          "organizeImportsNumericCollation": false,
          "organizeImportsTypeOrder": "last",
          "preferTypeOnlyAutoImports": false,
          "providePrefixAndSuffixTextForRename": true,
          "provideRefactorNotApplicableReason": true,
          "quotePreference": "auto"
        }
      }
    }
Info 1512 [09:57:58.425] Host configuration update for file /path/to/my/project/users-table/columns.tsx
Info 1513 [09:57:58.425] response:
    {"seq":0,"type":"response","command":"configure","request_seq":5,"success":true}
Perf 1514 [09:57:58.425] 5::configure: async elapsed time (in milliseconds) 1.3742
Info 1515 [09:57:58.436] request:
    {
      "seq": 6,
      "type": "request",
      "command": "completionInfo",
      "arguments": {
        "file": "/path/to/my/project/users-table/columns.tsx",
        "line": 14,
        "offset": 30,
        "triggerKind": 1
      }
    }
Info 1516 [09:57:58.458] getCompletionData: Get current token: 0.05774999999994179
Info 1517 [09:57:58.459] getCompletionData: Is inside comment: 0.0039590000014868565
Info 1518 [09:57:58.459] getCompletionData: Get previous token: 0.09445899999991525
Info 1519 [09:57:58.459] getCompletionsAtPosition: isCompletionListBlocker: 0.21216700000150013
Info 1520 [09:57:58.463] getCompletionData: Semantic work: 3.269209000001865
Info 1521 [09:57:58.478] getCompletionsAtPosition: getCompletionEntriesFromSymbols: 15.02716700000019
Perf 1522 [09:57:58.479] 6::completionInfo: elapsed time (in milliseconds) 42.8923
Info 1523 [09:57:58.479] response:
    {"seq":0,"type":"response","command":"completionInfo","request_seq":6,"success":true,"body":{"flags":0,"isGlobalCompletion":false,"isMemberCompletion":true,"isNewIdentifierLocation":false,"optionalReplacementSpan":{"start":{"line":14,"offset":17},"end":{"line":14,"offset":30}},"entries":[{"name":"action","kind":"property","kindModifiers":"","sortText":"11"},
...
{"name":"staticStatusText","kind":"property","kindModifiers":"","sortText":"11"},
...
{"name":"viewPage","kind":"property","kindModifiers":"","sortText":"11"}]}}
Info 1524 [09:57:58.535] request:
    {
      "seq": 7,
      "type": "request",
      "command": "signatureHelp",
      "arguments": {
        "file": "/path/to/my/project/users-table/columns.tsx",
        "line": 14,
        "offset": 30
      }
    }
Perf 1525 [09:57:58.536] 7::signatureHelp: elapsed time (in milliseconds) 1.1674
Info 1526 [09:57:58.536] response:
    {"seq":0,"type":"response","command":"signatureHelp","request_seq":7,"success":false,"message":"No content available."}
Info 1527 [09:57:58.987] request:
    {
      "seq": 8,
      "type": "request",
      "command": "change",
      "arguments": {
        "file": "/path/to/my/project/users-table/columns.tsx",
        "line": 14,
        "offset": 17,
        "endLine": 14,
        "endOffset": 30,
        "insertString": ""
      }
    }
Perf 1528 [09:57:58.988] 8::change: async elapsed time (in milliseconds) 0.7891
Info 1529 [09:57:59.288] request:
    {
      "seq": 9,
      "type": "request",
      "command": "geterr",
      "arguments": {
        "delay": 0,
        "files": [
          "/path/to/my/project/users-table/columns.tsx"
        ]
      }
    }
Perf 1530 [09:57:59.289] 9::geterr: async elapsed time (in milliseconds) 0.3514
Info 1531 [09:57:59.290] Starting updateGraphWorker: Project: /path/to/my/project/tsconfig.app.json
Info 1532 [09:57:59.391] Finishing updateGraphWorker: Project: /path/to/my/project/tsconfig.app.json projectStateVersion: 2 projectProgramVersion: 1 structureChanged: false structureIsReused:: Completely Elapsed: 100.59912500000064ms
Info 1533 [09:57:59.391] Different program with same set of files
Info 1534 [09:57:59.391] event:
    {"seq":0,"type":"event","event":"syntaxDiag","body":{"file":"/path/to/my/project/users-table/columns.tsx","diagnostics":[{"start":{"line":14,"offset":17},"end":{"line":14,"offset":18},"text":"Identifier expected.","code":1003,"category":"error"}]}}
Info 1535 [09:57:59.391] request:
    {
      "seq": 10,
      "type": "request",
      "command": "change",
      "arguments": {
        "file": "/path/to/my/project/users-table/columns.tsx",
        "line": 14,
        "offset": 16,
        "endLine": 14,
        "endOffset": 17,
        "insertString": ""
      }
    }
Perf 1536 [09:57:59.392] 10::change: async elapsed time (in milliseconds) 0.0538
Info 1537 [09:57:59.392] Starting updateGraphWorker: Project: /path/to/my/project/tsconfig.app.json
Info 1538 [09:57:59.438] Finishing updateGraphWorker: Project: /path/to/my/project/tsconfig.app.json projectStateVersion: 3 projectProgramVersion: 1 structureChanged: false structureIsReused:: Completely Elapsed: 45.8761250000025ms
Info 1539 [09:57:59.438] Different program with same set of files
Info 1540 [09:58:11.725] event:
    {"seq":0,"type":"event","event":"requestCompleted","body":{"request_seq":9}}
Info 1541 [09:58:11.726] request:
    {
      "seq": 11,
      "type": "request",
      "command": "change",
      "arguments": {
        "file": "/path/to/my/project/users-table/columns.tsx",
        "line": 14,
        "offset": 16,
        "endLine": 14,
        "endOffset": 16,
        "insertString": "."
      }
    }
Perf 1542 [09:58:11.727] 11::change: async elapsed time (in milliseconds) 0.2430
Info 1543 [09:58:11.727] request:
    {
      "seq": 12,
      "type": "request",
      "command": "completionInfo",
      "arguments": {
        "file": "/path/to/my/project/users-table/columns.tsx",
        "line": 14,
        "offset": 17,
        "triggerCharacter": ".",
        "triggerKind": 2
      }
    }
Info 1544 [09:58:11.727] Starting updateGraphWorker: Project: /path/to/my/project/tsconfig.app.json
Info 1545 [09:58:11.777] Finishing updateGraphWorker: Project: /path/to/my/project/tsconfig.app.json projectStateVersion: 4 projectProgramVersion: 1 structureChanged: false structureIsReused:: Completely Elapsed: 50.56283299999632ms
Info 1546 [09:58:11.777] Different program with same set of files
Info 1547 [09:58:11.778] getCompletionData: Get current token: 0.004625000001396984
Info 1548 [09:58:11.778] getCompletionData: Is inside comment: 0.0012080000014975667
Info 1549 [09:58:11.778] getCompletionData: Get previous token: 0.01316699999733828
Info 1550 [09:58:11.778] getCompletionsAtPosition: isCompletionListBlocker: 0.0014169999994919635
Info 1551 [09:58:11.807] getCompletionData: Semantic work: 29.412084000003233
Info 1552 [09:58:11.809] getCompletionsAtPosition: getCompletionEntriesFromSymbols: 0.8271250000034343
Perf 1553 [09:58:11.809] 12::completionInfo: elapsed time (in milliseconds) 82.5199
Info 1554 [09:58:11.809] response:
    {"seq":0,"type":"response","command":"completionInfo","request_seq":12,"success":true,"performanceData":{"updateGraphDurationMs":50.56283299999632},"body":{"flags":0,"isGlobalCompletion":false,"isMemberCompletion":true,"isNewIdentifierLocation":false,"entries":[{"name":"action","kind":"property","kindModifiers":"","sortText":"11"},
...
{"name":"staticStatusText","kind":"property","kindModifiers":"","sortText":"11"},
...
{"name":"viewPage","kind":"property","kindModifiers":"","sortText":"11"}]}}
Info 1555 [09:58:11.810] request:
    {
      "seq": 14,
      "type": "request",
      "command": "change",
      "arguments": {
        "file": "/path/to/my/project/users-table/columns.tsx",
        "line": 14,
        "offset": 17,
        "endLine": 14,
        "endOffset": 17,
        "insertString": "s"
      }
    }
Perf 1556 [09:58:11.811] 14::change: async elapsed time (in milliseconds) 0.1501
Info 1557 [09:58:11.811] request:
    {
      "seq": 15,
      "type": "request",
      "command": "change",
      "arguments": {
        "file": "/path/to/my/project/users-table/columns.tsx",
        "line": 14,
        "offset": 18,
        "endLine": 14,
        "endOffset": 18,
        "insertString": "t"
      }
    }
Perf 1558 [09:58:11.811] 15::change: async elapsed time (in milliseconds) 0.0809
Info 1559 [09:58:11.811] request:
    {
      "seq": 16,
      "type": "request",
      "command": "change",
      "arguments": {
        "file": "/path/to/my/project/users-table/columns.tsx",
        "line": 14,
        "offset": 19,
        "endLine": 14,
        "endOffset": 19,
        "insertString": "a"
      }
    }
Perf 1560 [09:58:11.811] 16::change: async elapsed time (in milliseconds) 0.0497
Info 1561 [09:58:11.811] request:
    {
      "seq": 17,
      "type": "request",
      "command": "change",
      "arguments": {
        "file": "/path/to/my/project/users-table/columns.tsx",
        "line": 14,
        "offset": 20,
        "endLine": 14,
        "endOffset": 20,
        "insertString": "t"
      }
    }
Perf 1562 [09:58:11.811] 17::change: async elapsed time (in milliseconds) 0.1163
Info 1563 [09:58:11.811] request:
    {
      "seq": 19,
      "type": "request",
      "command": "change",
      "arguments": {
        "file": "/path/to/my/project/users-table/columns.tsx",
        "line": 14,
        "offset": 21,
        "endLine": 14,
        "endOffset": 21,
        "insertString": "i"
      }
    }
Perf 1564 [09:58:11.811] 19::change: async elapsed time (in milliseconds) 0.0375
Info 1565 [09:58:11.811] request:
    {
      "seq": 20,
      "type": "request",
      "command": "completionInfo",
      "arguments": {
        "file": "/path/to/my/project/users-table/columns.tsx",
        "line": 14,
        "offset": 22,
        "triggerKind": 1
      }
    }
Info 1566 [09:58:11.811] Starting updateGraphWorker: Project: /path/to/my/project/tsconfig.app.json
Info 1567 [09:58:11.857] Finishing updateGraphWorker: Project: /path/to/my/project/tsconfig.app.json projectStateVersion: 5 projectProgramVersion: 1 structureChanged: false structureIsReused:: Completely Elapsed: 45.571499999998196ms
Info 1568 [09:58:11.857] Different program with same set of files
Info 1569 [09:58:11.857] getCompletionData: Get current token: 0.004125000006752089
Info 1570 [09:58:11.857] getCompletionData: Is inside comment: 0.0012920000008307397
Info 1571 [09:58:11.857] getCompletionData: Get previous token: 0.015625
Info 1572 [09:58:11.857] getCompletionsAtPosition: isCompletionListBlocker: 0.0016669999968144111
Info 1573 [09:58:11.891] getCompletionData: Semantic work: 34.343375000004016
Info 1574 [09:58:11.892] getCompletionsAtPosition: getCompletionEntriesFromSymbols: 0.24224999999569263
Perf 1575 [09:58:11.892] 20::completionInfo: elapsed time (in milliseconds) 80.8877
Info 1576 [09:58:11.892] response:
    {"seq":0,"type":"response","command":"completionInfo","request_seq":20,"success":true,"performanceData":{"updateGraphDurationMs":45.571499999998196},"body":{"flags":0,"isGlobalCompletion":false,"isMemberCompletion":true,"isNewIdentifierLocation":false,"optionalReplacementSpan":{"start":{"line":14,"offset":17},"end":{"line":14,"offset":22}},"entries":[{"name":"action","kind":"property","kindModifiers":"","sortText":"11"},
...
{"name":"staticStatusText","kind":"property","kindModifiers":"","sortText":"11"},
...
{"name":"viewPage","kind":"property","kindModifiers":"","sortText":"11"}]}}
Info 1577 [09:58:11.892] request:
    {
      "seq": 21,
      "type": "request",
      "command": "change",
      "arguments": {
        "file": "/path/to/my/project/users-table/columns.tsx",
        "line": 14,
        "offset": 22,
        "endLine": 14,
        "endOffset": 22,
        "insertString": "c"
      }
    }
Perf 1578 [09:58:11.893] 21::change: async elapsed time (in milliseconds) 0.2788
Info 1579 [09:58:11.893] request:
    {
      "seq": 22,
      "type": "request",
      "command": "completionInfo",
      "arguments": {
        "file": "/path/to/my/project/users-table/columns.tsx",
        "line": 14,
        "offset": 23,
        "triggerKind": 1
      }
    }
Info 1580 [09:58:11.893] Starting updateGraphWorker: Project: /path/to/my/project/tsconfig.app.json
Info 1581 [09:58:11.939] Finishing updateGraphWorker: Project: /path/to/my/project/tsconfig.app.json projectStateVersion: 6 projectProgramVersion: 1 structureChanged: false structureIsReused:: Completely Elapsed: 46.48145800000202ms
Info 1582 [09:58:11.939] Different program with same set of files
Info 1583 [09:58:11.940] getCompletionData: Get current token: 0.00466700000106357
Info 1584 [09:58:11.940] getCompletionData: Is inside comment: 0.0012500000011641532
Info 1585 [09:58:11.940] getCompletionData: Get previous token: 0.011709000005794223
Info 1586 [09:58:11.940] getCompletionsAtPosition: isCompletionListBlocker: 0.0020409999997355044
Info 1587 [09:58:11.967] getCompletionData: Semantic work: 27.126083000002836
Info 1588 [09:58:11.967] getCompletionsAtPosition: getCompletionEntriesFromSymbols: 0.2093749999985448
Perf 1589 [09:58:11.967] 22::completionInfo: elapsed time (in milliseconds) 74.5362
Info 1590 [09:58:11.967] response:
    {"seq":0,"type":"response","command":"completionInfo","request_seq":22,"success":true,"performanceData":{"updateGraphDurationMs":46.48145800000202},"body":{"flags":0,"isGlobalCompletion":false,"isMemberCompletion":true,"isNewIdentifierLocation":false,"optionalReplacementSpan":{"start":{"line":14,"offset":17},"end":{"line":14,"offset":23}},"entries":[{"name":"action","kind":"property","kindModifiers":"","sortText":"11"},
...
{"name":"staticStatusText","kind":"property","kindModifiers":"","sortText":"11"},
...
{"name":"viewPage","kind":"property","kindModifiers":"","sortText":"11"}]}}
Info 1591 [09:58:11.968] request:
    {
      "seq": 24,
      "type": "request",
      "command": "change",
      "arguments": {
        "file": "/path/to/my/project/users-table/columns.tsx",
        "line": 14,
        "offset": 23,
        "endLine": 14,
        "endOffset": 23,
        "insertString": "S"
      }
    }
Perf 1592 [09:58:11.968] 24::change: async elapsed time (in milliseconds) 0.1558
Info 1593 [09:58:11.968] request:
    {
      "seq": 26,
      "type": "request",
      "command": "change",
      "arguments": {
        "file": "/path/to/my/project/users-table/columns.tsx",
        "line": 14,
        "offset": 24,
        "endLine": 14,
        "endOffset": 24,
        "insertString": "t"
      }
    }
Perf 1594 [09:58:11.968] 26::change: async elapsed time (in milliseconds) 0.0712
Info 1595 [09:58:11.968] request:
    {
      "seq": 27,
      "type": "request",
      "command": "completionInfo",
      "arguments": {
        "file": "/path/to/my/project/users-table/columns.tsx",
        "line": 14,
        "offset": 25,
        "triggerKind": 1
      }
    }
Info 1596 [09:58:11.968] Starting updateGraphWorker: Project: /path/to/my/project/tsconfig.app.json
Info 1597 [09:58:12.011] Finishing updateGraphWorker: Project: /path/to/my/project/tsconfig.app.json projectStateVersion: 7 projectProgramVersion: 1 structureChanged: false structureIsReused:: Completely Elapsed: 43.34833399999479ms
Info 1598 [09:58:12.011] Different program with same set of files
Info 1599 [09:58:12.012] getCompletionData: Get current token: 0.003833999995549675
Info 1600 [09:58:12.012] getCompletionData: Is inside comment: 0.005249999994703103
Info 1601 [09:58:12.012] getCompletionData: Get previous token: 0.01070899999467656
Info 1602 [09:58:12.012] getCompletionsAtPosition: isCompletionListBlocker: 0.004000000000814907
Info 1603 [09:58:12.040] getCompletionData: Semantic work: 27.964124999998603
Info 1604 [09:58:12.040] getCompletionsAtPosition: getCompletionEntriesFromSymbols: 0.2006660000042757
Perf 1605 [09:58:12.040] 27::completionInfo: elapsed time (in milliseconds) 72.2202
Info 1606 [09:58:12.040] response:
    {"seq":0,"type":"response","command":"completionInfo","request_seq":27,"success":true,"performanceData":{"updateGraphDurationMs":43.34833399999479},"body":{"flags":0,"isGlobalCompletion":false,"isMemberCompletion":true,"isNewIdentifierLocation":false,"optionalReplacementSpan":{"start":{"line":14,"offset":17},"end":{"line":14,"offset":25}},"entries":[{"name":"action","kind":"property","kindModifiers":"","sortText":"11"},
...
{"name":"staticStatusText","kind":"property","kindModifiers":"","sortText":"11"},
...
{"name":"viewPage","kind":"property","kindModifiers":"","sortText":"11"}]}}
Info 1607 [09:58:12.041] request:
    {
      "seq": 28,
      "type": "request",
      "command": "change",
      "arguments": {
        "file": "/path/to/my/project/users-table/columns.tsx",
        "line": 14,
        "offset": 25,
        "endLine": 14,
        "endOffset": 25,
        "insertString": "a"
      }
    }
Perf 1608 [09:58:12.041] 28::change: async elapsed time (in milliseconds) 0.1732
Info 1609 [09:58:12.041] request:
    {
      "seq": 29,
      "type": "request",
      "command": "completionInfo",
      "arguments": {
        "file": "/path/to/my/project/users-table/columns.tsx",
        "line": 14,
        "offset": 26,
        "triggerKind": 1
      }
    }
Info 1610 [09:58:12.041] Starting updateGraphWorker: Project: /path/to/my/project/tsconfig.app.json
Info 1611 [09:58:12.090] Finishing updateGraphWorker: Project: /path/to/my/project/tsconfig.app.json projectStateVersion: 8 projectProgramVersion: 1 structureChanged: false structureIsReused:: Completely Elapsed: 48.59087499999441ms
Info 1612 [09:58:12.090] Different program with same set of files
Info 1613 [09:58:12.090] getCompletionData: Get current token: 0.004708000000391621
Info 1614 [09:58:12.090] getCompletionData: Is inside comment: 0.0012080000014975667
Info 1615 [09:58:12.090] getCompletionData: Get previous token: 0.09470900000451365
Info 1616 [09:58:12.090] getCompletionsAtPosition: isCompletionListBlocker: 0.0015000000057625584
Info 1617 [09:58:12.117] getCompletionData: Semantic work: 26.514750000002095
Info 1618 [09:58:12.117] getCompletionsAtPosition: getCompletionEntriesFromSymbols: 0.1940000000031432
Perf 1619 [09:58:12.117] 29::completionInfo: elapsed time (in milliseconds) 76.1278
Info 1620 [09:58:12.117] response:
    {"seq":0,"type":"response","command":"completionInfo","request_seq":29,"success":true,"performanceData":{"updateGraphDurationMs":48.59087499999441},"body":{"flags":0,"isGlobalCompletion":false,"isMemberCompletion":true,"isNewIdentifierLocation":false,"optionalReplacementSpan":{"start":{"line":14,"offset":17},"end":{"line":14,"offset":26}},"entries":[{"name":"action","kind":"property","kindModifiers":"","sortText":"11"},
...
{"name":"staticStatusText","kind":"property","kindModifiers":"","sortText":"11"},
...
{"name":"viewPage","kind":"property","kindModifiers":"","sortText":"11"}]}}
Info 1621 [09:58:12.117] request:
    {
      "seq": 30,
      "type": "request",
      "command": "geterr",
      "arguments": {
        "delay": 0,
        "files": [
          "/path/to/my/project/users-table/columns.tsx"
        ]
      }
    }
Perf 1622 [09:58:12.118] 30::geterr: async elapsed time (in milliseconds) 0.1194
Info 1623 [09:58:12.119] event:
    {"seq":0,"type":"event","event":"syntaxDiag","body":{"file":"/path/to/my/project/users-table/columns.tsx","diagnostics":[]}}
Info 1624 [09:58:24.888] event:
    {"seq":0,"type":"event","event":"requestCompleted","body":{"request_seq":30}}
Info 1625 [09:58:24.889] request:
    {
      "seq": 31,
      "type": "request",
      "command": "completionEntryDetails",
      "arguments": {
        "file": "/path/to/my/project/users-table/columns.tsx",
        "line": 14,
        "offset": 26,
        "entryNames": [
          "staticStatusText"
        ]
      }
    }
Info 1626 [09:58:24.896] getCompletionData: Get current token: 0.015874999997322448
Info 1627 [09:58:24.896] getCompletionData: Is inside comment: 0.005333000000973698
Info 1628 [09:58:24.896] getCompletionData: Get previous token: 0.015249999996740371
Info 1629 [09:58:24.896] getCompletionsAtPosition: isCompletionListBlocker: 0.0016250000044237822
Info 1630 [09:58:24.921] getCompletionData: Semantic work: 25.310624999998254
Perf 1631 [09:58:32.132] 31::completionEntryDetails: elapsed time (in milliseconds) 7242.8328
Info 1632 [09:58:32.133] response:
    {"seq":0,"type":"response","command":"completionEntryDetails","request_seq":31,"success":true,"body":[{"name":"staticStatusText","kindModifiers":"","kind":"property","displayParts":[{"text":"(","kind":"punctuation"},{"text":"property","kind":"text"},{"text":")","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"staticStatusText","kind":"propertyName"},{"text":":","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"(","kind":"punctuation"},{"text":"accessor","kind":"parameterName"},{"text":":","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"AccessorEntity","kind":"aliasName"},{"text":"<","kind":"punctuation"},{"text":"Transaction","kind":"aliasName"},{"text":">","kind":"punctuation"},{"text":",","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"config","kind":"parameterName"},{"text":":","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"StatusColumnConfig","kind":"interfaceName"},{"text":")","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"=>","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"ColumnDef","kind":"aliasName"},{"text":"<","kind":"punctuation"},{"text":"Transaction","kind":"aliasName"},{"text":",","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"unknown","kind":"keyword"},{"text":">","kind":"punctuation"}],"documentation":[{"text":"Status column using Status component","kind":"text"}],"tags":[]}]}
Info 1633 [09:58:32.134] request:
    {
      "seq": 32,
      "type": "request",
      "command": "completionEntryDetails",
      "arguments": {
        "file": "/path/to/my/project/users-table/columns.tsx",
        "line": 14,
        "offset": 26,
        "entryNames": [
          "staticStatusText"
        ]
      }
    }
Info 1634 [09:58:32.134] getCompletionData: Get current token: 0.008541999995941296
Info 1635 [09:58:32.134] getCompletionData: Is inside comment: 0.0031670000025769696
Info 1636 [09:58:32.134] getCompletionData: Get previous token: 0.012042000002111308
Info 1637 [09:58:32.134] getCompletionsAtPosition: isCompletionListBlocker: 0.0012500000011641532
Info 1638 [09:58:32.134] getCompletionData: Semantic work: 0.4447909999944386
Perf 1639 [09:58:32.139] 32::completionEntryDetails: elapsed time (in milliseconds) 5.1246
Info 1640 [09:58:32.139] response:
    {"seq":0,"type":"response","command":"completionEntryDetails","request_seq":32,"success":true,"body":[{"name":"staticStatusText","kindModifiers":"","kind":"property","displayParts":[{"text":"(","kind":"punctuation"},{"text":"property","kind":"text"},{"text":")","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"staticStatusText","kind":"propertyName"},{"text":":","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"(","kind":"punctuation"},{"text":"accessor","kind":"parameterName"},{"text":":","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"AccessorEntity","kind":"aliasName"},{"text":"<","kind":"punctuation"},{"text":"Transaction","kind":"aliasName"},{"text":">","kind":"punctuation"},{"text":",","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"config","kind":"parameterName"},{"text":":","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"StatusColumnConfig","kind":"interfaceName"},{"text":")","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"=>","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"ColumnDef","kind":"aliasName"},{"text":"<","kind":"punctuation"},{"text":"Transaction","kind":"aliasName"},{"text":",","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"unknown","kind":"keyword"},{"text":">","kind":"punctuation"}],"documentation":[{"text":"Status column using Status component","kind":"text"}],"tags":[]}]}
Info 1641 [09:58:32.139] request:
    {
      "seq": 33,
      "type": "request",
      "command": "geterr",
      "arguments": {
        "delay": 0,
        "files": [
          "/path/to/my/project/users-table/columns.tsx"
        ]
      }
    }
Perf 1642 [09:58:32.139] 33::geterr: async elapsed time (in milliseconds) 0.0929
Info 1643 [09:58:32.140] request:
    {
      "seq": 34,
      "type": "request",
      "command": "change",
      "arguments": {
        "file": "/path/to/my/project/users-table/columns.tsx",
        "line": 14,
        "offset": 17,
        "endLine": 14,
        "endOffset": 26,
        "insertString": "staticStatusText"
      }
    }
Perf 1644 [09:58:32.140] 34::change: async elapsed time (in milliseconds) 0.0811
Info 1645 [09:58:32.140] event:
    {"seq":0,"type":"event","event":"requestCompleted","body":{"request_seq":33}}
Info 1646 [09:58:32.155] request:
    {
      "seq": 35,
      "type": "request",
      "command": "completionInfo",
      "arguments": {
        "file": "/path/to/my/project/users-table/columns.tsx",
        "line": 14,
        "offset": 33,
        "triggerKind": 1
      }
    }
Info 1647 [09:58:32.155] Starting updateGraphWorker: Project: /path/to/my/project/tsconfig.app.json
Info 1648 [09:58:32.225] Finishing updateGraphWorker: Project: /path/to/my/project/tsconfig.app.json projectStateVersion: 9 projectProgramVersion: 1 structureChanged: false structureIsReused:: Completely Elapsed: 70.12275000000227ms
Info 1649 [09:58:32.225] Different program with same set of files
Info 1650 [09:58:32.226] getCompletionData: Get current token: 0.004166000006080139
Info 1651 [09:58:32.226] getCompletionData: Is inside comment: 0.0012500000011641532
Info 1652 [09:58:32.226] getCompletionData: Get previous token: 0.013375000002270099
Info 1653 [09:58:32.226] getCompletionsAtPosition: isCompletionListBlocker: 0.0023339999970630743
Info 1654 [09:58:32.253] getCompletionData: Semantic work: 27.872792000001937
Info 1655 [09:58:32.254] getCompletionsAtPosition: getCompletionEntriesFromSymbols: 0.23249999999825377
Perf 1656 [09:58:32.254] 35::completionInfo: elapsed time (in milliseconds) 99.0496
Info 1657 [09:58:32.254] response:
    {"seq":0,"type":"response","command":"completionInfo","request_seq":35,"success":true,"performanceData":{"updateGraphDurationMs":70.12275000000227},"body":{"flags":0,"isGlobalCompletion":false,"isMemberCompletion":true,"isNewIdentifierLocation":false,"optionalReplacementSpan":{"start":{"line":14,"offset":17},"end":{"line":14,"offset":33}},"entries":[{"name":"action","kind":"property","kindModifiers":"","sortText":"11"},
...
{"name":"staticStatusText","kind":"property","kindModifiers":"","sortText":"11"},
...
{"name":"viewPage","kind":"property","kindModifiers":"","sortText":"11"}]}}
Info 1658 [09:58:32.264] request:
    {
      "seq": 36,
      "type": "request",
      "command": "signatureHelp",
      "arguments": {
        "file": "/path/to/my/project/users-table/columns.tsx",
        "line": 14,
        "offset": 33
      }
    }
Perf 1659 [09:58:32.264] 36::signatureHelp: elapsed time (in milliseconds) 0.7148
Info 1660 [09:58:32.264] response:
    {"seq":0,"type":"response","command":"signatureHelp","request_seq":36,"success":false,"message":"No content available."}
Info 1661 [09:58:32.443] request:
    {
      "seq": 37,
      "type": "request",
      "command": "geterr",
      "arguments": {
        "delay": 0,
        "files": [
          "/path/to/my/project/users-table/columns.tsx"
        ]
      }
    }
Perf 1662 [09:58:32.443] 37::geterr: async elapsed time (in milliseconds) 0.1107
Info 1663 [09:58:32.444] event:
    {"seq":0,"type":"event","event":"syntaxDiag","body":{"file":"/path/to/my/project/users-table/columns.tsx","diagnostics":[]}}
```

**Comment by babucarr32** [comment]
> It might help to see the tsserver logs. You can enable those using `initializationOptions` - https://github.com/typescript-language-server/typescript-language-server/blob/master/docs/configuration.md#tsserver-options
> 
> One thing that looks a bit weird is that Helix:
> 
>     * tries to resolve the same completion twice
> 
>     * the first resolve is done after completion was applied which seems a little late and potentially pointless. The other resolve happens even later.

Yes, the behavior is a bit weird.

**Comment by rchl** [comment]
Are you able to test with latest version of TypeScript? 5.0.0 is pretty old at this point. It might be something that was already fixed there.

I doubt there is any issue with the LSP server itself...

**Comment by babucarr32** [comment]
I updated to TypeScript `5.9.2`. But the problem still persists.
I am beginning to believe this("Alternatively it could also be related to the project itself and its configuration."). 
I only experience this problem in this specific project only! Even the `hover` is crazy slow sometimes in this project.

I will dig deep into the project.
Thank you for your time @rchl Appreciate it.

**Comment by malobre** [comment]
I believe I'm hitting something similar and looking at my logs nothing seems wrong on the lsp server side.

@babucarr32 have you opened an issue on the helix repo?

**Comment by babucarr32** [comment]
@malobre No, I didn't. For the most part I believe it's a configuration issue. Can you share you languages.toml (specifically typescript) configuration? the typescript version you are using?

**Comment by rchl** [comment]
@malobre I doubt that the changes introduced in 5.1.0 have anything to do with your issue. If it's anything like the original one then it was reported before 5.1.0 even existed.

What do the logs show? Is it the same case of completion resolving taking a long time?

**Comment by rchl** [comment]
I was able to reproduce the issue related to formatting changes but I think there are two different issues here.

The second one reported by @computerdane happens within the LSP layer and is due to a deadlock in Helix where it doesn't respond to `workspace/configuration` request during handling of `completionItem/resolve`.

The initial one seems to be due to slow response from `tsserver` but I'm not sure what exact circumstances trigger it.

**Comment by computerdane** [comment]
Just tried out PR #1043 and it fixed the issue. For steps to reproduce, I made a project real quick using `bun init`, opened the `index.ts` file, made a new line, typed `cons`, and pressed tab + enter to complete it to `console`.

Versions:

- helix 25.07.1 (a05c151b)
- typescript@5.9.3

**Comment by computerdane** [comment]
follow up: this bug was happening with other actions, such as renaming symbols, so i had to make my own fix that [removes all calls to fileConfigurationManager.ensureConfigurationForDocument](https://github.com/computerdane/typescript-language-server/commit/dddbd320977e9c26aa0d854e77f5a6cd1b20c5f1) in the meantime
