### ISSUE TITLE
Error: No Project. When starting LS from a bundled electron Theia application

### ISSUE THREAD

**Issue by kittaakos** [typescript-language-server/typescript-language-server#60]
I am not sure whether this issue belongs here or [Theia](https://github.com/theia-ide/theia/issues/new).

When I open a Theia workspace with installed `typescript` npm dependency I get the following error. Few more things to note:
 - I have the `tsserver` executable under `${theia_ws_root}/node_modules/.bin/`.
 - The bundled electron application itself [does **not** contain these executables](
https://github.com/theia-ide/theia/issues/1392#issuecomment-417880151) at runtime.

Terminal from Theia:
```
prprpr:theia akos.kitta$ pwd
/Users/akos.kitta/Desktop/theia
prprpr:theia akos.kitta$ which tsserver
prprpr:theia akos.kitta$ ./node_modules/.bin/tsserver --version
Content-Length: 76

{"seq":0,"type":"event","event":"typingsInstallerPid","body":{"pid":29149}}
^C
prprpr:theia akos.kitta$ tsserver --version
bash: tsserver: command not found
prprpr:theia akos.kitta$
```

Error:
```
root ERROR Error from definitions request: file:///Users/akos.kitta/Desktop/theia/packages/core/src/common/os.ts#32/16 Error: Request textDocument/definition failed with message: Error processing request. No Project.
Error: No Project.
    at Object.ThrowNoProject (/Users/akos.kitta/Desktop/theia/node_modules/typescript/lib/tsserver.js:92289:23)
    at ProjectService.getDefaultProjectForFile (/Users/akos.kitta/Desktop/theia/node_modules/typescript/lib/tsserver.js:94518:46)
    at IOSession.Session.getFileAndProjectWorker (/Users/akos.kitta/Desktop/theia/node_modules/typescript/lib/tsserver.js:96934:87)
    at IOSession.Session.getFileAndProject (/Users/akos.kitta/Desktop/theia/node_modules/typescript/lib/tsserver.js:96919:29)
    at IOSession.Session.getDefinition (/Users/akos.kitta/Desktop/theia/node_modules/typescript/lib/tsserver.js:96572:31)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/akos.kitta/Desktop/theia/node_modules/typescript/lib/tsserver.js:96044:61)
    at /Users/akos.kitta/Desktop/theia/node_modules/typescript/lib/tsserver.js:97580:88
    at IOSession.Session.executeWithRequestId (/Users/akos.kitta/Desktop/theia/node_modules/typescript/lib/tsserver.js:97571:28)
    at IOSession.Session.executeCommand (/Users/akos.kitta/Desktop/theia/node_modules/typescript/lib/tsserver.js:97580:33)
    at IOSession.Session.onMessage (/Users/akos.kitta/Desktop/theia/node_modules/typescript/lib/tsserver.js:97600:35)
    at Interface.<anonymous> (/Users/akos.kitta/Desktop/theia/node_modules/typescript/lib/tsserver.js:98831:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:280:10)
    at Interface._normalWrite (readline.js:422:12)
    at Socket.ondata (readline.js:139:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:597:20)
    at new ResponseError (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:95354:28)
    at handleResponse (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:94338:48)
    at processMessageQueue (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:94166:17)
    at Immediate._onImmediate (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:94150:13)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

**Comment by kittaakos** [comment]
It works when I install the `typescript` npm dependency to the global (`npm i -g typescript`) but it is not available from the Theia workspace.

Terminal from Theia:
```
prprpr:theia akos.kitta$ pwd
/Users/akos.kitta/Desktop/theia
prprpr:theia akos.kitta$ which tsserver
/Users/akos.kitta/.nvm/versions/node/v8.11.4/bin/tsserver
prprpr:theia akos.kitta$ tsserver --version
Content-Length: 76

{"seq":0,"type":"event","event":"typingsInstallerPid","body":{"pid":29514}}
^C
prprpr:theia akos.kitta$
```

Probably related to this: https://github.com/theia-ide/typescript-language-server/issues/28.

**Comment by mofux** [comment]
I'm having a similar problem, it also only happens when running the language server from the packaged electron app. It looks like inside the packaged bundle the environment variables differ from the ones that you get when launching the app from the command line. If you inspect `process.env.PATH` from within the bundled electron app you will notice that it's missing the paths to the installed node executables - in my case the PATH looks like this: 

```bash
/usr/bin:/bin:/usr/sbin:/sbin`
```

Running it through the shell shows this PATH which includes the paths to the node binary modules: 

```bash
/Users/user/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/user/Git/enter-client/node_modules/.bin:/Users/user/.nvm/versions/node/v10.15.1/bin:/Users/user/.yarn/bin:/Users/user/.config/yarn/global/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

I'm guessing the path is usually being set inside a `.bash_profile` or similar environment script that does not get invoked when starting the bundled electron app. Not sure if there is an easy way to fix it though.

**Comment by kittaakos** [comment]
> If you inspect `process.env.PATH` from within the bundled electron app you will notice that it's missing the paths to the installed node executables - in my case the PATH looks like this:

@mofux, what OS are you using? We used to have an issue with the `PATH` on macOS, but it was fixed with [this](https://github.com/theia-ide/theia/commit/381ff3942b951d6cce9ea26fd937433cd355a9ad).

Do you have the same problem if you [build an electron application locally](https://github.com/theia-ide/theia-apps/tree/master/theia-electron)?

**Comment by mofux** [comment]
@kittaakos Thanks for sharing your `fix-path` solution, that definitely seems to solve the path problem (I'm on MacOS). I'm still seeing a very strange problem though. When running in a bundled electron app (not theia, my own which uses typescript-language-server and monaco-languageclient) the `tsconfig.json` file does not seem to get resolved correctly from the language server. I don't get any obvious errors (`--tsserver-log-file` doesn't write a log file for some reason, so I can't inspect any deeper) and everything is working correctly, except that things like the `lib` section of my `tsconfig.json` are not being respected (I guess because they are never read). It doesn't happen when running the app with the electron executable directly.

Did you see a similar problem in Theia?

**Comment by kittaakos** [comment]
> running in a bundled electron app (not theia, my own which uses typescript-language-server and monaco-languageclient) the `tsconfig.json` file does not seem to get resolved correctly from the language server.

@akosyakov, can you please help with this?

> `--tsserver-log-file` doesn't write a log file for some reason, so I can't inspect any deeper

This might worth a bug report.

> Did you see a similar problem in Theia?

I am not aware of anything similar in Theia.

**Comment by mofux** [comment]
@kittaakos Thanks for the response. The problem appears whenever the `tsserver-path` points to a file that is inside application package (e.g. `/Applications/MyApp.app/Contents/Resources/app.asar.unpacked/node_modules/typescript/lib/tsserver.js`). In my case, I wanted to make sure that I can start the LS even if the application runs on a device that has no typescript installed, so I used the `--tsserver-path` option to point towards the `typescript` i'm shipping with my app. Not sure if OSX is sandboxing calls if the tsserver is started from within an application package.

**Comment by hinell** [comment]
I'm experiencing a similar problem in Neovim and getting ` Error: No Project.` error as well. See:

<details>
<summary>FILE: tsserver.log</summary>

```
Info 0    [12:09:24.718] Starting TS Server
Info 1    [12:09:24.719] Version: 5.2.2
Info 2    [12:09:24.719] Arguments: /home/alex/dotfiles/nvm/.nvm/versions/node/v20.5.0/bin/node ./TypeScript/node_modules/typescript/lib/tsserver.js --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName /tmp/6eb47b130a698bb88d59be24690b11c3/tscancellation* --logVerbosity normal --logFile /tmp/tsserver/tsserver-log-as5oK1/tsserver.log --locale en --validateDefaultNpmLocation --useNodeIpc
Info 3    [12:09:24.719] Platform: linux NodeVersion: v20.5.0 CaseSensitive: true
Info 4    [12:09:24.719] ServerMode: 1 hasUnknownServerMode: undefined
Info 5    [12:09:24.727] Host information neovim
Info 6    [12:09:24.727] Format host information updated
Info 7    [12:09:26.114] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
Info 8    [12:09:27.359] Finishing updateGraphWorker: Project: /dev/null/inferredProject1* Version: 1 structureChanged: true structureIsReused:: Not Elapsed: 1244.2914890013635ms
Info 9    [12:09:27.359] Project '/dev/null/inferredProject1*' (Inferred)
Info 10   [12:09:27.359] 	Files (8)

Info 11   [12:09:27.359] -----------------------------------------------
Info 12   [12:09:27.360] Project '/dev/null/inferredProject1*' (Inferred)
Info 12   [12:09:27.360] 	Files (8)

Info 12   [12:09:27.360] -----------------------------------------------
Info 12   [12:09:27.360] Open files: 
Info 12   [12:09:27.360] 	FileName: ./TypeScript/src/compiler/checker.ts ProjectRootPath: ./TypeScript/src/compiler
Info 12   [12:09:27.360] 		Projects: /dev/null/inferredProject1*
Info 12   [12:09:28.143] Project '/dev/null/inferredProject1*' (Inferred)
Info 12   [12:09:28.143] 	Files (8)

Info 12   [12:09:28.143] -----------------------------------------------
Info 12   [12:09:28.143] Open files: 
Info 12   [12:09:28.144] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
Info 13   [12:09:28.150] Finishing updateGraphWorker: Project: /dev/null/inferredProject1* Version: 2 structureChanged: true structureIsReused:: Not Elapsed: 6.382156999781728ms
Info 14   [12:09:28.150] Project '/dev/null/inferredProject1*' (Inferred)
Info 15   [12:09:28.150] 	Files (0)

Info 16   [12:09:28.150] -----------------------------------------------
Info 17   [12:09:28.150] Before ensureProjectForOpenFiles:
Info 18   [12:09:28.150] Project '/dev/null/inferredProject1*' (Inferred)
Info 18   [12:09:28.150] 	Files (0)

Info 18   [12:09:28.150] -----------------------------------------------
Info 18   [12:09:28.150] Open files: 
Info 18   [12:09:28.150] After ensureProjectForOpenFiles:
Info 19   [12:09:28.150] Project '/dev/null/inferredProject1*' (Inferred)
Info 19   [12:09:28.150] 	Files (0)

Info 19   [12:09:28.150] -----------------------------------------------
Info 19   [12:09:28.150] Open files: 
Err 19    [12:09:28.165] Exception on executing command {
  "seq": 4,
  "type": "request",
  "command": "navtree",
  "arguments": {
    "file": "./TypeScript/src/compiler/checker.ts"
  }
}:

    No Project.

    Error: No Project.
        at Object.ThrowNoProject (./TypeScript/node_modules/typescript/lib/tsserver.js:174959:11)
        at ScriptInfo.getDefaultProject (./TypeScript/node_modules/typescript/lib/tsserver.js:175711:23)
        at _ProjectService.doEnsureDefaultProjectForFile (./TypeScript/node_modules/typescript/lib/tsserver.js:178932:36)
        at _ProjectService.ensureDefaultProjectForFile (./TypeScript/node_modules/typescript/lib/tsserver.js:178927:75)
        at IpcIOSession.getFileAndProjectWorker (./TypeScript/node_modules/typescript/lib/tsserver.js:183899:77)
        at IpcIOSession.getFileAndProject (./TypeScript/node_modules/typescript/lib/tsserver.js:183885:17)
        at IpcIOSession.getFileAndLanguageServiceForSyntacticOperation (./TypeScript/node_modules/typescript/lib/tsserver.js:183888:36)
        at IpcIOSession.getNavigationTree (./TypeScript/node_modules/typescript/lib/tsserver.js:184320:44)
        at navtree (./TypeScript/node_modules/typescript/lib/tsserver.js:182604:43)
        at ./TypeScript/node_modules/typescript/lib/tsserver.js:184838:69
        at IpcIOSession.executeWithRequestId (./TypeScript/node_modules/typescript/lib/tsserver.js:184830:14)
        at IpcIOSession.executeCommand (./TypeScript/node_modules/typescript/lib/tsserver.js:184838:29)
        at IpcIOSession.onMessage (./TypeScript/node_modules/typescript/lib/tsserver.js:184880:51)
        at process.<anonymous> (./TypeScript/node_modules/typescript/lib/tsserver.js:186461:14)
        at process.emit (node:events:514:28)
        at emit (node:internal/child_process:951:14)
        at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

</details>

### Steps to reproduce
Install:
```
NVIM v0.10.0-dev-8405649f92
node v20.5.0 or v18.18.0
npm i -g typescript-language-server@4.0.0
npm i -g typescript@5.2
```

1. Set LSP server init [option](https://github.com/typescript-language-server/typescript-language-server#initializationoptions) `logDirectory : "/tmp/tsserver/"`

2. Run test project `TypeScript`
```bash
# problem reproduction bash script
pushd $(mktemp -d)
git clone --no-tags --depth 1 git@github.com:microsoft/TypeScript.git
pushd TypeScript
rm /tmp/tsserver/tsserver-log-*/*.log
nvim-x compiler/checker.ts &
sleep 3s && nvim-x -c "cd /tmp/tsserver" -p /tmp/tsserver/tsserver-log-*/*.log

```

**Comment by rchl** [comment]
The client should open the file (in the LSP sense) first. It doesn't seem like it's doing that from the log file.
Also not sure what 'nvim-x' is.

**Comment by hinell** [comment]
@rchl Sorry, for bothering. It turned out that [LunarVim/bigfile.nvim](https://github.com/LunarVim/bigfile.nvim) plugin was involved.  The issue arises if LSP client is detached from and editor buffer on big files. That plugin was doing that all the time.

 It's fixed by disabling the said plugin in config.

Has nothing to do with this repo.

**Comment by rchl** [comment]
I don't know what this issue is about and there is not enough info to understand it.

If it's still an issue and someone cares about it then please provide TSSERVER logs (`initializationOptions.tsserver.logVerbosity: 'verbose'`).
